name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        include:
          - os: macos-latest
            build_command: python setup.py py2app
            artifact_name: macos-Snap-OCR-executable
          - os: windows-latest
            build_command: pyinstaller --onefile main.py
            artifact_name: windows-Snap-OCR-executable

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller py2app

    - name: Build executable
      run: ${{ matrix.build_command }}

    - name: List contents of dist directory
      run: ls dist

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.artifact_name }}
        path: dist/*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download macOS artifacts
      uses: actions/download-artifact@v2
      with:
        name: macos-Snap-OCR-executable
        path: ./macos-Snap-OCR-executable

    - name: List contents of macOS artifact directory
      run: ls ./macos-Snap-OCR-executable

    - name: Download Windows artifacts
      uses: actions/download-artifact@v2
      with:
        name: windows-Snap-OCR-executable
        path: ./windows-Snap-OCR-executable

    - name: List contents of Windows artifact directory
      run: ls ./windows-Snap-OCR-executable

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false

    - name: Upload macOS Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./macos-Snap-OCR-executable/*
        asset_name: macos-Snap-OCR-executable
        asset_content_type: application/octet-stream

    - name: Upload Windows Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./windows-Snap-OCR-executable/*
        asset_name: windows-Snap-OCR-executable
        asset_content_type: application/octet-stream
